brace_style = "PreferSameLine"
combine_control_expr = false
condense_wildcard_suffixes = true
edition = "2018"
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
hard_tabs = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
where_single_line = true
